# Generated by Django 3.2.11 on 2022-01-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='opened',
        ),
    ]
