# Generated by Django 3.2.11 on 2022-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_shop_opened'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityModel',
        ),
        migrations.RenameModel(
            old_name='Street',
            new_name='StreetModel',
        ),
    ]
