# Generated by Django 3.2.11 on 2022-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220125_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street_city', to='app1.citymodel', verbose_name='Город'),
        ),
    ]
