# Generated by Django 3.2.11 on 2022-01-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_streetmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.citymodel', verbose_name='Город'),
        ),
    ]
