# Generated by Django 3.2.11 on 2022-01-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_streetmodel_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='ShopModel',
        ),
    ]
