# Generated by Django 3.2.11 on 2022-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_shop_shopmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Название улицы'),
        ),
    ]
