# Generated by Django 3.2.11 on 2022-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220125_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopModel',
            new_name='Shop',
        ),
    ]
