# Generated by Django 3.2.11 on 2022-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_shop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название города'),
        ),
    ]
